config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :posts
  get 'profiles/index'
  mount Sidekiq::Web, at: "/sidekiq" if Rails.env.development?

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }

  resources :profiles, only: [:index, :edit, :update, :show]
  resources :users
  resources :posts, only: [:index, :new]

  root to: "profiles#show"
end

app/models/profile.rb
class Profile < ApplicationRecord

    mount_uploader :image, ImageUploader
    
    belongs_to :user
    has_one_attached :image

    validates :name, presence: true
    validates :email, presence: true
    validates :password, presence: true

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @profile = current_user.profile
  end

  def show
  end
  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.prepare_profile
    @profile.assign_attributes(profile_params)
    if @profile.save  :validate => false
      redirect_to profile_path, notice: 'プロフィールを更新しました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(
      :email,
      :name,
      :image
    )
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.haml
.container
  %ul
    - @profile.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div
      = f.label :image, 'イメージ画像'
    %div
      = f.file_field :image

    %div
      = f.label :name, 'アカウント名'
    %div
      = f.text_field :name, class: 'text'

    %div
      = f.label :email, 'メールアドレス'
    %div
      = f.text_field :email, class: 'text'

    = f.submit '保存', class: 'btn-primary'

app/views/profiles/index.html.haml
- redirect_to profile_path if @user == current_user

app/views/profiles/show.html.haml
.container.profilePage

  // ブラウザバックアイコン
  .profilePage_site_backer
    = link_to :back do
      %i.fas.fa-arrow-left.fa-3x

  // ユーザー要素
  .profilePage_user
    .profilePage_user_name
      = current_user.name
    .user_icon
      = image_tag current_user.avatar_image.url, class: 'profilePage_user_image'

  .profilePage_user_actionButton
    - if current_user
      = link_to 'Edit', edit_profile_path(current_user.id)
    - else
      = 'Follow'

= link_to 'ホームへ', posts_path(current_user.id)
// 投稿数
// フォロワーの数
// フォロー数
// 投稿している画像